import './globals.css'
import { Inter } from 'next/font/google'
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Orientation 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="../../public/favicon.ico" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
